In [1]:
%pip install torch
%pip install transformers

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 4.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 99.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 74.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 61.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 5.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 12.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 5.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 76.4 MB/s eta 0:00:00
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlin

In [2]:
%pip install wget

  Preparing metadata (setup.py) ... done
  Created wheel for wget: filename=wget-3.2-py3-none-any.whl size=9656 sha256=c37c7e9855f7d26853a82c650b5fe55173c871267354380a7d304eac80ac7066
  Stored in directory: /root/.cache/pip/wheels/40/b3/0f/a40dbd1c6861731779f62cc4babcb234387e11d697df70ee97
Successfully built wget


In [3]:
!wget https://raw.githubusercontent.com/microsoft/CodeBERT/master/UniXcoder/unixcoder.py

--2025-03-05 22:52:10--  https://raw.githubusercontent.com/microsoft/CodeBERT/master/UniXcoder/unixcoder.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.109.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10352 (10K) [text/plain]
Saving to: ‘unixcoder.py’

unixcoder.py        100%[===================>]  10.11K  --.-KB/s    in 0.001s  

2025-03-05 22:52:11 (11.2 MB/s) - ‘unixcoder.py’ saved [10352/10352]



Import UniXCoder and torch
  - Test if CUDA is installed in the device, if not, it will use CPU instead

In [4]:
from unixcoder import UniXcoder
import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = UniXcoder("microsoft/unixcoder-base-nine")
model.to(device)

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/1.11k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/938k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/444k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/772 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/691 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/504M [00:00<?, ?B/s]

UniXcoder(
  (model): RobertaModel(
    (embeddings): RobertaEmbeddings(
      (word_embeddings): Embedding(51416, 768, padding_idx=1)
      (position_embeddings): Embedding(1026, 768, padding_idx=1)
      (token_type_embeddings): Embedding(10, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): RobertaEncoder(
      (layer): ModuleList(
        (0-11): 12 x RobertaLayer(
          (attention): RobertaAttention(
            (self): RobertaSdpaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): RobertaSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): Layer

Encoder-Only mode
  1. Code and NL Embeddings

In [8]:
# Encode maximum function
func = "def f(a,b): return a if a > b else return b"
tokens_ids = model.tokenize([func], max_length=512, mode="<encoder-only>")
source_ids = torch.tensor(tokens_ids).to(device)
tokens_embeddings, max_func_embeddings = model(source_ids)

# Encode minimum function
func = "def f(a,b): return a if a < b else return b"
tokens_ids = model.tokenize([func], max_length=512, mode="<encoder-only>")
source_ids = torch.tensor(tokens_ids).to(device)
tokens_embeddings, min_func_embeddings = model(source_ids)

# Encode natural language
nl = "return maximum value"
tokens_ids = model.tokenize([nl], max_length=512, mode="<encoder-only>")
source_ids = torch.tensor(tokens_ids).to(device)
tokens_embeddings, nl_embeddings = model(source_ids)

print(max_func_embeddings.shape)
print(max_func_embeddings)


torch.Size([1, 768])
tensor([[ 5.6580e-01, -1.0380e+00, -1.4834e+00,  1.1743e+00,  4.3048e-01,
          4.9323e-01,  1.2657e+00, -2.4183e+00,  6.7862e-02,  1.5474e-01,
         -9.2393e-01,  6.8328e-01, -1.2149e+00,  8.9989e-01,  2.7802e+00,
          1.8232e-01,  3.1748e+00,  1.1020e+00, -2.7630e-01, -1.8928e+00,
         -2.2688e+00, -5.1272e-01,  2.9094e-02,  9.9918e-01,  1.9216e+00,
         -1.7340e+00, -3.8972e-01,  2.3788e+00,  2.0569e+00,  1.6664e-01,
          1.9595e+00, -6.4137e-01, -2.4268e+00,  2.1778e+00, -3.7297e-01,
         -1.1871e+00,  2.0935e+00,  7.1688e-02,  3.1702e-01, -2.8031e-01,
         -1.5677e+00,  2.6065e+00, -1.6594e+00, -2.5327e+00, -3.7530e+00,
         -1.2979e+00, -3.6520e-01,  1.9881e+00, -6.7426e-01,  1.0974e+00,
         -2.2144e+00, -5.0786e-01, -2.1933e+00,  5.1287e-01,  2.1589e+00,
          7.7407e-01, -2.6550e-01, -9.6862e-01, -1.0549e+00,  1.0636e+00,
         -1.7096e-01, -1.1498e+00, -1.1571e+00,  1.6551e+00, -2.1183e+00,
         -1.1857e

2. Similarity between code and NL
  - Normalize two embeddings (Min and Max)
  - Calculate the cosine similarity between two embedded vectors (Dot Product)

In [9]:
norm_max_func_embeddings = torch.nn.functional.normalize(max_func_embeddings, p=2, dim=1)
norm_min_func_embeddings = torch.nn.functional.normalize(min_func_embeddings, p=2, dim=1)
norm_nl_embedding = torch.nn.functional.normalize(nl_embeddings, p=2, dim=1)

# Calculate the similarity
max_func_nl_similarity = torch.einsum("ac,bc->ab",norm_max_func_embeddings, norm_nl_embedding)
min_func_nl_similarity = torch.einsum("ac,bc->ab", norm_min_func_embeddings, norm_nl_embedding)

print(max_func_nl_similarity)
print(min_func_nl_similarity)


tensor([[0.3180]], device='cuda:0', grad_fn=<ViewBackward0>)
tensor([[0.1974]], device='cuda:0', grad_fn=<ViewBackward0>)


## Code Search Tasks
1. NL to Code (Code Completion)
2. Code to Text (Code Summarization)